### ISSUE TITLE
将单函数类判断成了SAM

### ISSUE THREAD

**Issue by pfmiles** [pfmiles/kilim-fiber#1]
```
public class App {

public static void main(String[] args) {
    final Task task = new Task() {

        @Override
        public void execute() throws Pausable {
            System.out.println("hello");
            Foo f = new Foo();
            f.hehe();
            System.out.println("world");
        }

    };
    task.run();
    System.out.println("hey there");
    task.run();
    System.out.println("at last...");
}

public static class Foo {

    public void hehe() throws Pausable {
        System.out.println("foo hehe");
        new Bar().haha();
        System.out.println("Foo hehe end");
    }

    public void test() {
    }
}

public static class Bar {

    public void haha() throws Pausable {
        System.out.println("haha");
        Task.yield();
        System.out.println("hoho");
    }

    public void test() {
    }

}
}
```

上述代码，若Foo或Bar中任意一个的test方法被删除，则会报错：

```
Exception in thread "main" java.lang.RuntimeException: task is done with exception
at kilim.Task._runExecute(Task.java:318)
at kilim.Task.run(Task.java:328)
at test.App.main(App.java:23)
Caused by: java.lang.IncompatibleClassChangeError: Found class test.App$Bar, but interface was     expected
at test.App$Foo.$shim$1(App.java)
at test.App$Foo.hehe(App.java:33)
at test.App$1.execute(App.java:18)
at kilim.Task._runExecute(Task.java:303)
... 2 more
```

原因是kilim的ClassWeaver将只有一个方法的类错判成了jdk8的functional interface，从而为其生成了SAM(single abstract method) methods

**Comment by pfmiles** [comment]
对于interface也是同样的情况：对只有一个方法的interface，按照SAM的方式处理了；这种处理方式在jdk8以前的jvm上都不适用
